# Generated by Django 3.2.22 on 2023-10-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=' Click and Visit', max_length=255),
        ),
    ]
